# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            明月秦关
tagline:          'haipeng的博客'
description:      '❀代码❉生活❀'
url:              https://jinglehp.github.io

author:
  name:           'Haipeng Wang'
  url:            https://jinglehp.github.io 

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://jinglehp.github.io
